Improvements
twilio-infra-as-code/outbound-messaging pull request #5
Opened 2021-06-03 12:27 UTC by vernig

This PR includes: 

* Add a README.md with installation and usage instructions. The instructions provide workaround for https://github.com/twilio-infra-as-code/twilio-pulumi-provider/issues/4 and  https://github.com/twilio-infra-as-code/plugin-twilio-infra/issues/22
* Change `name` attribute for new task created to destination phone number (currently hardcoded to `Kaique Lupo`)
* Change `chatUserFriendlyName` to destination phone number (currently hardcoded to `Kaique Lupo`)

Fix #4 
Fix #3

2021-06-04 17:28 UTC, bermudezmt requested changes

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +1. Install Twilio CLI following [these instructions](https://www.twilio.com/docs/twilio-cli/quickstart)
``

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +1. Install Twilio CLI following [these instructions](https://www.twilio.com/docs/twilio-cli/quickstart)
```suggestion
1. [Install the Twilio CLI] (https://www.twilio.com/docs/twilio-cli/quickstart)
```

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +1. Install the Infra Plugin for Twilio CLI
for the Twilio CLI

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +4. Login to the project using
Log in

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +8. In the Twilio [Console Settings page for Flex](https://www.twilio.com/console/flex/settings) make sure that the "Enable Dialpad" is Enabled
toggle "Enable Dialpad" to `Enabled`.

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +1. In Flex click the dialpad button (next to the microhpne on the top right corner). At the bottom of the dialpad you will find the "Outbound SMS" section.
In Flex, click the Dialpad 

Correct: microphone

"At the bottom of the Dialpad, you will find the additional "Outbound SMS" text field.

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +1. Type the destination number and press on START
Enter the destination number and click **Start**.

2021-06-04 17:28 UTC, bermudezmt commented on README.md
> +1. A new Task / Reservation is generated: Click the accpet button to accept and start chatting
Clicking start generates a new [Task](https://www.twilio.com/docs/flex/admin-guide/core-concepts/routing#tasks). Click **Accept** to accept the incoming task and start a messaging conversation with the customer.

2021-06-07 08:53 UTC, vernig commented
Thanks @bermudezmt for the (thorough) review and the changes. I added them all. 

@kaiquelupo could you have a look to the PR as well, especially commit 8168534ef0783ad90beaa8471e2d99c74a5c469e? 

Feel free to merge into master if you are happy with it

2021-06-22 13:16 UTC, kaiquelupo approved these changes

2021-06-22 13:16 UTC, merged